kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: epp-metrics-reader
subjects:
- kind: ServiceAccount
  name: vllm-llama3-8b-instruct-epp
  namespace: nrozenba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: epp-metrics-reader