apiVersion: v1
kind: Pod
metadata:
 name: guidellm
 namespace: nrozenba
spec:
  containers:
  - name: guidellm
    image: ghcr.io/vllm-project/guidellm:v0.5.3
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
    command:
    - /bin/bash
    - -c
    args:
    - |
      sleep infinity
    volumeMounts:
    - mountPath: /data
      name: outputdata
  volumes:
    - name: outputdata
      persistentVolumeClaim:
        claimName: guidellm-results-pvc